
version: 0
index_id: reviews

index_uri: s3://quickwit/index

doc_mapping:
  field_mappings:
    - name: p_e_id
      type: text
      stored: true
      tokenizer: default
      record: position
      fast: true
    - name: text
      type: text
      tokenizer: default
      record: position
      stored: true
      fast: true

search_settings:
  default_search_fields: [text]
