version: '3.7'


services:
  minio:
    hostname: minio
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z
    command: server --console-address ":9001" minio/data

    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"

      # environment:
      # MINIO_ROOT_USER: minioadmin
      # MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    hostname: mc
    container_name: mc
    image: minio/mc
    environment:
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./data/reviews:/data
      - ./scripts:/home/scripts
    entrypoint: ["/bin/sh", "-c", "/home/scripts/data-upload.sh"]
    depends_on:
      - minio