version: '3.7'


services:
  minio:
    hostname: minio
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z
    command: server --console-address ":9001" minio/data

    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    hostname: mc
    container_name: mc
    image: minio/mc
    environment:
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
      - ./scripts:/home/scripts
    entrypoint: ["/bin/sh", "-c", "/home/scripts/bucket-creation.sh"]
    depends_on:
      - minio

  quickwit:
    hostname: quickwit
    container_name: quickwit
    image: quickwit/quickwit
    entrypoint: ["/bin/sh", "-c", "/home/scripts/indexing-review-data.sh"]
    ports:
      - "7280:7280"
    environment:
      QW_S3_ENDPOINT: ${MINIO_HOST}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}

    volumes:
      - ./quickwit-config:/quickwit/qwdata
      - ./data:/data
      - ./scripts:/home/scripts
    depends_on:
      - minio-client
    links:
      - "minio"


  clickhouse:
    hostname: clickhouse
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    volumes:
      - ./data/:/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  datazeit-api:
    hostname: datazeit-api
    container_name: api
    build: .
    ports:
      - "8000:80"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    depends_on:
      - clickhouse
      - minio-client
    links:
      - "quickwit"
      - "clickhouse"